---
title: "Media"
output: postcards::trestles

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<font size="+2">2024</font>
<p> <a href="https://www.nytimes.com/2024/02/15/health/abortion-pills-mail-safety.html" style="color:black;"> **New York Times**, “Abortions by Telemedicine and Mailed Pills Are Safe and Effective, Study Finds” <br></a>
<a href="https://www.statnews.com/2024/02/15/telehealth-medication-abortion-safe-effective-study-finds/" style="color:black;">**Stat News**, “Abortion pills offered via telehealth as safe as in-person medication abortions, study finds” <br></p></a>

<font size="+2">2023</font>
<p><a href="https://www.motherjones.com/politics/2024/02/a-new-study-on-medication-abortion-refutes-the-arguments-conservatives-are-taking-to-the-supreme-court//" style="color:black;">**Mother Jones**, “A New Study on Medication Abortion Refutes the Arguments Conservatives Are Taking to the Supreme Court”<br></a>
<a href="https://coloradonewsline.com/2023/10/11/abortion-rights-advocates-say-consequences-dire-if-scotus-declines-to-hear-pill-case/" style="color:black;"> **States Newsroom**, “Abortion rights advocates say consequences dire if SCOTUS declines to hear pill case”<br></a>
<a href="https://www.hcn.org/issues/55.4/south-public-health-navigating-the-new-health-care-deserts" style="color:black;"> **High Country News**, “Navigating the new healthcare deserts: Post-Roe, startups help those seeking abortion shrink travel distances and carbon emissions”<br></a>
<a href="https://www.nytimes.com/interactive/2023/04/01/health/abortion-pill-safety.html?smid=tw-nytimes&smtyp=cur" style="color:black;">**New York Times**, “Are Abortion Pills Safe? Here’s the Evidence.”<br></a>
<a href="https://www.msnbc.com/morning-joe/watch/how-the-covid-pandemic-impacted-family-planning-164418629829" style="color:black;"> **MSNBC, Morning Joe**, “How the COVID pandemic impacted family planning”<br></a>
<a href="https://www.forbes.com/sites/debgordon/2023/02/28/women-less-keen-to-get-pregnant-since-the-pandemic-began-new-study-shows/?sh=1e6527e073dc" style="color:black;">**Forbes**, “Women less keen to get pregnant since the pandemic began, new study shows”<br></p></a>
