---
title: "Other writing"
output: postcards::trestles

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<font size="+2"> Book chapters </font>
<p> **Koenig LR**, Li M. Achieving Gender Equality: Understanding Gender Equality and Health among Vulnerable Adolescents in the Sustainable Development Goals Era. In P. Banati, editor, Sustainable Development Across the Life Course: Evidence from Longitudinal Research. 2020. Bristol University Press.</p> 

<font size="+2"> Reports and Opinion Editorials </font>	
<p> <a href="https://theconversation.com/telehealth-makes-timely-abortions-possible-for-many-research-shows-219076" style="color:black;"> **Koenig LR**, Upadhyay UD. Telehealth makes timely abortions possible for many, research shows. The Conversation. 2024. </a> <br>
<p> <a href="https://societyfp.org/wp-content/uploads/2023/09/SFP_ScienceSays_Template-TelehealthMedicationAbortion-f.pdf" style="color:black;">**Koenig LR**, Becker A, Upadhyay UD. Telehealth medication abortion is safe and effective. Society of Family Planning. 2023. </a> <br>
<p> <a href="https://www.publichealthpost.org/research/telehealth-abortion/" style="color:black;">**Koenig LR**, Upadhyay UD. Virtual Clinics Offer Safe and Effective Abortion Care. Public Health Post. 2021. </a> <br>
<p> <a href="https://www.ansirh.org/sites/default/files/2021-06/medication-abortion-safety_2021_FINAL.pdf" style="color:black;">Zia Y, **Koenig LR**, Ko J, Upadhyay U. Safety and effectiveness of first-trimester medication abortion in the United States. Oakland, California: Advancing New Standards in Reproductive Health. </a><br></p>
